### ISSUE TITLE
Demo link is not working

### ISSUE THREAD

**Issue by ZouZou** [angular-material-extensions/calendar#2]
Hi,

I am trying to open the demo link, however it says that the page does not exist (404)
is the only work around to clone this repo?

Regards,

**Comment by michaeldoye** [comment]
This project is currently under development and has not gone through a release cycle yet. You can watch the repo to get notified when the first release is ready :)

**Comment by handihow** [comment]
Angular Material Calendar would be... awesome.. watching the repo for new releases

**Comment by AnthonyNahas** [comment]
@handihow this library is on my roadmap
